akrennmair/newsbeuter

- src/colormanager.cpp
Hi,
Instead of:
```Loading configuration...Error while processing command `color non_element blue white' (/home/digenis/.newsbeuter/config line 1): `non_element' is not a valid configuration element```
I 've been getting:
```Loading configuration...Error while processing command `color non_element blue white' (/home/digenis/.newsbeuter/config line 1): ``%s' is not a valid configuration element' is not a valid configuration element```
> Missing var for %s formating of exception message

- src/rss.cpp
Fix an abnormal termination which happens when a GUID is lost due to the item being updated or deleted by the fetch thread when the web browser command is running in the main thread. When the browser finishes, newsbeuter attempts to find the item being read and calls abort() on failure.
This crash is more frequent when using text-mode browsers (e.g. w3m) which, unlike the graphical ones, do not return immediately.
This fix is more a hack than a proper one. The problem was exposed when a lock was added to method rss_feed::get_item_by_guid_unlocked() in commit d71336f48be10df737b811edc7796d6a9a88498e. After that, failure to find the item resulted in abort() being called. This fix brings back the dummy item introduced in commit 8dd8a153f8fd5b2fb86eb74e842ffe621c0ea4ba, avoiding the crash …
> Fix crash when a GUID is lost while browsing command is running

- config.sh
Fixes json detection case when:
1. the system has "json" package, but too old a version
2. the system has an up-to-date "json-c" version
3. config.sh exits immediately after the first step
> config.sh: check_pkg: do return instead of exit

- src/itemlist_formaction.cpp
itempos becomes arbitrarily large when there is no item left. Make sure to
only access visible_items < size().
Steps to reproduce:
- Set show-read-articles no.
- Show last unread article in feed.
- Press q.
- Press space.
- Press n.
> Fix segfault in jump_to_next_unread_item

- include/configcontainer.h
- src/configcontainer.cpp
Macro `va_start` must not be used with reference types, but is actually used with `std::string&`. This change basically replaces passing-by-reference with passing-by-value. It's less optimal than passing by reference but more robust.
> Possible fix for the issue #135

- po/ja.po
Hi, there.  Newsbeuter is great.  I hope you are proud of it.
Here is a patch that attempts to remedy newsbeuter's lack of Japanese localization.  I am not a native speaker of Japanese, but I have lived in Japan for about a decade and have worked as a technical translator.  The patch is not complete but covers the important parts.  I hope to complete it after encountering more strings "in the wild" (and will be stress-testing newsbeuter in the meantime).
Thank you and take care.
> Japanese Localization File

- src/cache.cpp
When exiting newsbeuter with only one rss feed in `~.newsbeuter/urls`, [src/cache.cpp:568] (https://github.com/akrennmair/newsbeuter/blob/50c713cbc8d7f889dc2029dfc24702ec31fef114/src/cache.cpp#L568) generates a list of one element with extra quotes, which reqults in an SQL statement that looks like this,
```SQL
DELETE FROM rss_feed WHERE rssurl NOT IN ('https://www.archlinux.org/feeds/news/''');
DELETE FROM rss_item WHERE feedurl NOT IN ('https://www.archlinux.org/feeds/news/''');
```
and the extra quotes are messing with the search results,
```
sqlite> select * from rss_feed where rssurl NOT IN ('https://www.archlinux.org/feeds/news/''');
https://www.archlinux.org/feeds/news/|https://www.archlinux.org/news/|Arch Linux: Recent news updates|0|0|
sqlite> select * from rss_feed where rssurl …
```
> Prevent cache deletion when one feed is configured

- src/feedhq_api.cpp
This fixes a bug where the custom feedhq URL configuration setting
wasn't added for this API call. This resulted in the request to generate
the URL token failing with a `CURLE_URL_MALFORMAT` `CURLcode`. This
stopped calls such as marking an item or all items as read to fail.
> Fix feedhq API token URL

- src/newsblur_api.cpp
Various fixes for the Newsblur API. It now handles tags correctly (like The Old Reader API) and doesn't crash on "dummy" articles.
> Fix newsblur API

- config.sh
Newsbeuter doesn't recognise new ncurses version when it's hardcoded to specific config program (issue #198). This checks using pkg-config first.
> Use pkg-config to search for ncursesw.

- doc/newsbeuter.txt
this only works if one calls open-in-browser instead of just open
> fix example for macro that executes external command via set-browser

- contrib/colorschemes/solarized-dark
- contrib/colorschemes/solarized-light
The current solarized-dark color scheme doesn't work properly on _all_ terminals, and in some cases the colors may show wrong. I fixed that, and made it look a little bit more similar to "[mutt solarized](https://raw.github.com/altercation/solarized/master/img/screen-mutt-dark.png)." I also added a complementing light scheme.
> Update solarized-dark colorscheme, and add solarized-light

- src/feedlist_formaction.cpp
- stfl/feedlist.stfl
This allows the use of listnormal_unread and listfocus_unread colors to the feedlist, making it consistent with the itemlist.
If a feed has any unread articles, it applies the listnormal_unread/listfocus_unread. For feeds with no unread articles, listnormal and listfocus are applied as usual.
Thanks!
> Apply listnormal_unread and listfocus_unread colors to feedlist

- doc/newsbeuter.txt
- include/itemview_formaction.h
- src/itemview_formaction.cpp
This adds the formatting option %F to itemview-title-format which allows for displaying the feed title in the header of the article view.
> Add feed title to itemview-title-format

- src/rss_parser.cpp
The pointer returned by string.c_str becomes invalid after the string is
destroyed. Apparently original code happened to work for options shorter
than ~20 characters.
> Fix config handling in rss_parser::download_http

- po/de.po
- po/es.po
- po/es_ES.po
- po/fr.po
- po/hu.po
- po/it.po
- po/ja.po
- po/nb.po
- po/newsbeuter.pot
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/sv.po
- po/tr.po
- po/uk.po
- po/zh.po
- po/zh_TW.po
- src/controller.cpp
- src/pb_controller.cpp
- src/view.cpp
This PR fixes the following mistakes:
* Corrects a typo (occured -> occurred)
* Corrects the log entry of the open_in_pager function.
* Corrects the long version of the -q podbeuter argument, it should be --queue-file not --quiet.
> Small corrections.

- src/cache.cpp
- test/cache.cpp
The original attempt to fix the bug with read/unread status (#137) was quite far from the good solution, so I've decided to rewrite it from scratch.
I'm looking forward for feedback, especially on the test. I had very little C++ practice during several past years so there might be stupid errors in the code.
> Set up cache for items in the search result

- include/controller.h
- include/rss.h
- src/cache.cpp
- src/controller.cpp
- src/feedlist_formaction.cpp
- src/itemlist_formaction.cpp
controller::search_for_items accepts a feedurl string and passes it down to the
cache. Since query feeds are not stored in the cache this causes all query feed
searches to return no results. The solution is to pass the feed object to
search_for_items and do a linear search from the items that have been already
loaded/matched if we are searching a query feed.
Also added an assert call in cache::search_for_items to prevent bugs like this in the future.
Fixes #313
> Allow searching in query feeds

- src/htmlrenderer.cpp
- test/htmlrenderer.cpp
Make the html renderer strip newline characters from the text to prevent them from being passed down to stfl and causing rendering errors.
(Perhaps they should be replaced with a space character?)
> HTMLRenderer: Strip newline characters

- include/tagsouppullparser.h
- src/htmlrenderer.cpp
- src/tagsouppullparser.cpp
- test/tagsouppullparser.cpp
Tagsouppullparser used camelCase for a few functions, switched to snake_case to be consistent with the rest of the project.
> Consistency fix

- doc/configcommands.dsv
- doc/example-config
- rss/parser.cpp
- rss/rsspp.h
- src/configcontainer.cpp
- src/rss_parser.cpp
- src/utils.cpp
Currently newsbeuter performs no validation on SSL certificates. Until a better solution is implemented (per feed SSL control) a global setting is better than doing no validation at all.
> Add config option to control SSL validation

- src/formaction.cpp
Dumpconfig used the token index 1 for the parameter probably assuming 0 was the
command itself. This is incorrect as the command is stripped off of the tokens
array earlier, this made dumpconfig use empty memory(or in the worst case
garbage) as the filename and effectively breaking it completely.
> Fix dumpconfig

- doc/keycmds.dsv
- src/itemlist_formaction.cpp
This fixes Issue #330, and will make sure an item is undeleted when and item is toggled unread.
Please correct me if I'm not doing this right -- I haven't contributed on Github that much.  It's late Friday, I'm in a mood, so I picked one of the top issues that you had tagged.
> Toggle unread article also now undeletes (#330)

- include/utils.h
- src/stflpp.cpp
- src/utils.cpp
Some iconv() implementations don't support transliteration.
When iconv with //TRANSLIT is first attempted and fails,
try again without it, and remember the result.
Fixes #364
Fixes #174
> Check for iconv() TRANSLIT support

- src/view.cpp
This change hides the terminal cursor in the Newsbeuter UI. Fairly straightforward.
This also fixes #344.
> Hide the cursor

- rss/atom_parser.cpp
- rss/rss_09x_parser.cpp
- rss/rsspp_internal.h
- test/data/atom10_1.xml
- test/data/rss092_1.xml
- test/rss.cpp
Hi,
the atom parser (mostly) supports an xml:base attribute being used to define the base-path for relative links in the entries. This pull-request "copies" this support to the RSS 0.9x and by extend 2.0 (aka: I haven't tried implementing it in RSS 1.0) fixing atom in the process and extending the tests slightly.
The usage of the attribute (and relative links) isn't very common I guess, but e.g. tweeper (https://git.ao2.it/tweeper.git/) generates RSS feeds with it and atom was already supporting it so it shouldn't be entirely useless, "just" obscure as a feature.
Lightly tested with my feeds to not crash and burn instantly (or after a few feed reloads), but I have no prior experience with newsbeuter-code, so there might be gotchas. You have been warned.
Thanks for considering & best …
> support xml:base in RSS 0.9x and 2.0

- include/htmlrenderer.h
- include/textformatter.h
- src/controller.cpp
- src/htmlrenderer.cpp
- src/itemview_formaction.cpp
- src/textformatter.cpp
- test/htmlrenderer.cpp
- test/textformatter.cpp
This PR fixes 2 issues with line wrapping:
* `nonwrappable` line types still got wrapped at the screen border which made the name misleading and offered no real way to disable wrapping entirely. Fixed this by renaming the current functionality to `softwrappable` and introducing `nonwrappable` which passes the text without wrapping or any other operations.
* HTML tables were marked as wrappable when they shouldn't be.
> Fix table alignment & wrapping

- src/feedlist_formaction.cpp
Query feeds only exist in memory, if open-in-browser was called on a query feed
it would simply open a browser to the users home directory, which is obviously
erroneous behaviour.
> Don't allow query feeds to be opened in browser

- rss/parser.cpp
The `If-None-Match` header combined with the `A-IM: feed` header instructs
compatible servers to only send the feed entries that have been added or
changed since the feed was last updated. (As determined using the ETag sent
by the server which is later returned by the If-None-Match header.)
No other changes required than adding this header. Supported by ExpressionEngine, Textpattern, and Liferea. I’m working on adding support to all the major open source feed readers, and will submit patches to WordPress as well.
> Support for delta feeds (RFC3229+feed)

- rss/parser.cpp
I did a mistake with pull request #390. The header should be sent if either If-None-Match or/and If-Last-Modified headers are also sent to match other implementations.
> Send A-IM header with either etag or lastmod

- test/textformatter.cpp
A test case in textformatter lacked the leading spaces it was supposed to test
for.
> Improve description for one of textformatter tests

- src/keymap.cpp
The width of the tab character varies from setup to setup which breaks
alignment. Using spaces is better since it has a standard length.
> Don't use tabs for alignment

- test/itemlist_formaction.cpp
- Fixes issue 409 by ensuring each url opened by OP_OPENALLINBROWSER
or OP_OPENALLINBROWSER_AND_MARK is opened exactly once.
- Fixes issue 410 by matching urls opened by OP_OPENALLINBROWSER
or OP_OPENALLINBROWSER_AND_MARK independently of the order they were
opened.
> Fix itemlist_formaction testing

- doc/keycmds.dsv
Add missing documentation for the hard-quit key(`Q`)
> Document hard-quit shortcut

- Makefile
- config.h
Include the commit hash in the version if built from git to ease debugging.
> Include the git commit hash in the version macro

- src/poddlthread.cpp
Previously, we were using a, now removed, function called mkdir_p to
create the directories for the podbeuter download. That function had a
bug(or was it a feature?) that always ignored the last part of the path.
This worked with the current setup well since it was only passed paths
that included a filename that should be ignored when created the
directories anyway.
In f1dd88e4a4e31c5945a12cbbef6d99df28cad67d it was changed to use
mkdir_parents and mkdir_p was removed. This caused all the files
podbeuter was trying to download to be created as directories instead of
regular files, causing all subsequent attempts to write to them to fail.
> Don't use make_parents with the filename

- src/help_formaction.cpp
- src/view.cpp
This fixes the oversight in #379.
> Make cursor visible when in a cmdline

- include/utils.h
- src/textformatter.cpp
- src/utils.cpp
- test/utils.cpp
Whitespace consolidation was done in tokenize_spaced() which was used
from the wrap_lines function. To account for softwrappable lines, which
we don't want to consolidate the whitespace on, the behaviour of
tokenize_spaced what changed from consolidating whitespace to simply
tokenizing and leaving whitespace intact. Consolidation was moved to the
new consolidate_whitespace() function.
> Separate line wrapping and whitespace consolidation

- src/rss.cpp
- test/rss.cpp
This modifies the rss_item::sort_flags function in rss.cpp in order to
correct two bugs in the way it cleans up the input flags. Changes are :
- sort_flags no longer fails to remove more than one following or identiqual
non alphabetic characters.
- sort_flags no longer removes extra characters when a letter appears
twice in the flag list.
Fixes #436 #437 #438
Link to build : https://travis-ci.org/akrennmair/newsbeuter/builds/179715117
> Clean up incorrect article flags

- doc/configcommands.dsv
- doc/example-config
- src/configcontainer.cpp
- src/utils.cpp
The proxy type socks5h does the hostname resolution on the proxy instead
of the client (hence the name) and is therefore preferred with e.g Tor.
The socks5 type allows a client to do either with most performing the
DNS lookup locally and asking the socks5-proxy server to connect to a
specific IPv4/6. That can fail if the server has another network setup –
like no IPv6 – and in terms of Tor it means that DNS queries are leaked
and .onion addresses aren't working.
> add support for the socks5h proxy type

- include/htmlrenderer.h
- src/htmlrenderer.cpp
HTML has up to 6 header elements([source](http://www.w3schools.com/html/html_headings.asp)), newsbeuter only supported up to h4.
> Fix h5 and h6 html elements not being handled

- doc/newsbeuter.txt
An OpenBSD commiter just sent me this: https://twitter.com/blakkheim/status/819266247628115973
So OpenBSD is able to run Newsbeuter :)
> Deleted outdated comment on OpenBSD

- src/rss_parser.cpp
- src/utils.cpp
- test/utils.cpp
Try to deduce title from url only if the parsed title is empty. This happens with some blogs which don't populate the title properly.
This patch uses the already existing function make_title, although it is improved to not include .html or .htm at the end of the title.
> deduce article title from url if it is empty

- Makefile
A makefile assignment with `=` will be expanded every time it is
referenced. This meant that the git command would be run every time it
was referenced in a compiler call.
Instead, it is better to use `:=` which expands the value once when it is
assigned. This prevents multiple calls to git saving a few precious CPU
cycles.
> Evaluate the commit hash once when compiling

- src/tagsouppullparser.cpp
- src/utils.cpp
- test/utils.cpp
Hi,
I have a feed (https://www.heute.de/?view=rss) which includes "sometimes" completely broken items, which due to newsbeuter trying to generate a title for those items results in an abort by an unhandled exception. The commit in the "middle" is fixing the abort in the util function, but perhaps on a more global view newsbeuter maybe shouldn't act on strange items.
Anyway, I stumbled over two tiny other things in the process and have that included here as well as I was too lazy to make independent pullrequest for it, but if you prefer I will try to be less lazy. ;)
Best regards
David
> dont abort on empty title in utils::make_title

- doc/chapter-firststeps.txt
AsciiDoc only (seems to) interpret backticks as "representing code" if they are balanced. The previous documentation only contained a single backtick. By extending the documentation and adding another backtick everything in between was interpreted as code.
Escaping the first backtick seems to fix this. Interestingly you only have to and only can escape the first backtick. Which could lead to the same behavior in the long run if other backticks are added.
Fun fact: #334 linked to another issue fittingly named "Consider checking if backticks in config are balanced" :smile:
> Fix broken documentation introduced by fix for #334

- src/newsblur_api.cpp
Newsblur returns null if the feed is in their account but no longer
exists. Users should clean their feeds, this adds a log message in
case they have not. 
Closes #494
> feat: check if Newsblur feed link is null

- doc/configcommands.dsv
- doc/example-config
- include/ocnews_api.h
- src/configcontainer.cpp
- src/ocnews_api.cpp
- src/rss_parser.cpp
- src/utils.cpp
Looks we should allow curl access such https ownCloud sites just like
other clients did if user set ocnews-verifypeer to no.
I notice the #248 said will dispatch such certificate verification problems, too. Anyway, for some users, the feature is necessary ;)
Thanks.
> ssl-verify → ssl-verifypeer; add ssl-verifyhost

- Makefile
when linking binaries with g++, (random) filesystem order of input files
influences ordering of functions in the output
See https://reproducible-builds.org/ for why this matters.
> Make build reproducible

- doc/newsbeuter.txt
- src/ttrss_api.cpp
Currently, newsbeuter sets the HTTP-Auth parameter for all requests that
target the TTRSS-api from the "ttrss-login" and "ttrss-password" config
file options. This explicitly provided auth_info takes precedence over
optionally provided user-information in libcurl.
Therefore the following config settings
```
urls-source    "ttrss"
ttrss-url      "https://htuser:htpasswd@ttrssinstance.example.org"
ttrss-login    "ttrssuser"
ttrss-password "ttrsspasswd"
```
will try to query `trssinstance.example.org` with auth_info
`ttrssuser:ttrsspasswd` and consequently fail, while libcurl as such
would happily accept the auth info from `ttrss-url` when no explicit
auth-info was provided.
This commit rectifies this and consequently allows newsbeuter to use
multiuser-TTRSS instances which are hosted behind …
> TTRSS-API: only set auth_info for "Single" ttrss-mode

- include/view.h
- src/itemlist_formaction.cpp
- src/view.cpp
When opening a link the browser may return a value unequal to zero.
This gets recognized and then printed to stderr.
If this happens during the "open-in-browser-and-mark-read"-operation neither
the article in question is marked as read nor it is scrolled down.
Unfortunately I had to change the method declaration of open_in_browser from void
to bool in order to transmit one bit of information to the outside of that
particular function. Although this should not be an issue as this is
syntactically allowed similar a line of code only persisting of a literal.
> intercept browser's failure (issue #448)

- include/pb_controller.h
- include/pb_view.h
- include/utils.h
- include/view.h
- src/controller.cpp
- src/feedlist_formaction.cpp
- src/itemlist_formaction.cpp
- src/itemview_formaction.cpp
- src/list_formaction.cpp
- src/pb_controller.cpp
- src/pb_view.cpp
- src/urlview_formaction.cpp
- src/utils.cpp
- src/view.cpp
newsbeuter utilizes the system(3) function to run external programs.
Examples for external programs are a text editor, an extermal pager or the
browser.
Those external programs may return a non-zero exit code. This patch intercepts
in a such case and prints an error message as well as a debugging output.
> intercept browser's/pager's failure (issue #449)
